---
title: "Visualise fresh weight"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

## https://github.com/patricksnelgar/kiwifruit-graph-theory/blob/master/code/exploration.Rmd

library(readr)
library(dplyr)
library(magrittr)
library(here)
library(lubridate)
library(lattice)


# relational information for each of the quadrants
quadrant_info <- 
	data.frame(Quadrant = 1:36,
			   OffsetX = rep(c(1000, 500, 0, 0, 500, 1000), each = 6),
			   OffsetY = rep(c(2000, 1000, 0, 0, 1000, 2000), 6),
			   MultiplierX = rep(c(-1,1), each = 18),
			   MultiplierY = rep(rep(c(-1,1), each = 3), 6),
			   QuadrantFromLeader = rep(c(3:1, 1:3), 6), 
			   QuadrantFromTrunk = rep(c(3:1, 1:3), each = 6),
			   NorthSouth = rep(c("S", "N"), each = 18),
			   EastWest = rep(rep(
		   						  c("W", "E"), 
		   						  each = 3
		   						  ),
			   			   	  6)
			   )
# x&y coords for overlaying the quadrant IDs
# only works when vine is plotted with leader running horizontal (swap x and y).
quadrant_labels <- data.frame(x = rep(c(-1250, -750, -250, 250, 750, 1250), each = 6),
							  y = rep(c(2500, 1500, 500, -500, -1500, -2500), 6),
							  label = 1:36)
flowering_dates <- read_csv(here("input/flowering_dates.csv")) %>%
					mutate(FloweringColour = tolower(FloweringColour),
						   FloweringDate = dmy(FloweringDate))

source("../data_import/architecture_data_import_and_merge.R")
source("../data_import/shoot_leaf_area_import_and_plot.R")
source("../data_import/shoot_data_import_and_merge.R")
source("../data_import/fruit_data_import_and_merge.R")
```

## Visualize

```{r}
histogram(~ FreshWeight | factor(VineUUID), data=all_fruit_data, scales=list(alternating=FALSE), 
          between=list(x=0.3, y=0.3), breaks=30, layout=c(3,3))


qqmath(~ FreshWeight | factor(VineUUID), data=all_fruit_data,
       distribution = function(p) qnorm(p, mean=0, sd=1),
       scales=list(alternating=FALSE), between=list(x=0.3, y=0.3),
       breaks=30, layout=c(3,3),
       prepanel = prepanel.qqmathline,
       panel = function(x, ...) {
         panel.qqmath(x, ...)
         panel.qqmathline(x, ...)
       })


with(all_fruit_data, tapply(FreshWeight,  VineUUID, summary))
with(all_fruit_data, tapply(FreshWeight,  VineUUID, sd, na.rm=TRUE))

with(all_fruit_data, tapply(FreshWeight,  VineUUID, length))
```



```{r scratchpad, echo=FALSE, results="hide"}
xyplot( DryMatter ~ FreshWeight | factor(VineUUID), data=all_fruit_data, scales=list(alternating=FALSE), between=list(x=0.3, y=0.3), breaks=30, layout=c(3,3), pch=16, cex=0.3)

xyplot( DryMatter ~ FreshWeightSlice | factor(VineUUID), data=all_fruit_data, scales=list(alternating=FALSE), between=list(x=0.3, y=0.3), breaks=30, layout=c(3,3), pch=16, cex=0.3)
```